const menu = [
    {
    id: 1,
    title: 'Fresh Rolls',
    category: 'Appetizers',
    price: 7.99,
    img: './images/freshRolls.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
  },
  {
    id: 2,
    title: 'Miang Kham',
    category: 'Appetizers',
    price: 7.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 3,
    title: 'Som Tum',
    category: 'Appetizers',
    price: 6.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 4,
    title: 'Pad Thai',
    category: 'Noodles',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 5,
    title: 'Drunken Noodle',
    category: 'Noodles',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 6,
    title: 'Tom Yum Noodle soup',
    category: 'Noodles',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 7,
    title: 'Kapow',
    category: 'Entree',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 8,
    title: 'Pumpkin Curry',
    category: 'Entree',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 9,
    title: 'Avocado Green Curry',
    category: 'Entree',
    price: 17.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 10,
    title: 'Fried Rice',
    category: 'Entree',
    price: 10.99,
    img: './images/item-1.jpeg',
    desc: 'Jasmine brown rice stir-fried with soy-meat, onions, tomatoes, bell peppers, Thai basil, Chinese broccoli, and egg',
  }
]
export default menu